# array

### array is a data type that:
* items are stored in order
* each item is avalible by index for same time
* all items has common data type
* max len of items and amount of memmory set in advance


In [2]:
import numpy as np

In [4]:
arr_00 = np.array([1, 2, 3, 4, 5])
print(type(arr_00))
print(arr_00)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
arr_01 = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]
                  ])
print(arr_01)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### to set a date type
int64 is default date type for numpy

In [9]:
arr_00 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(type(arr_00))
print(type(arr_00[0]))
print(arr_00)

<class 'numpy.ndarray'>
<class 'numpy.int8'>
[1 2 3 4 5]


### to change a date type

In [10]:
arr_03 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(type(arr_03[0]))
arr_03 = np.int16(arr_03)
print(type(arr_03[0]))

<class 'numpy.int8'>
<class 'numpy.int16'>


In [11]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
nd_arr = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]
                  ], dtype=np.int16)

### to get dimension of array

In [19]:
print(arr.ndim, '1d')
print(nd_arr.ndim, '2d')

1 1d
2 2d


### to get all number of items of array

In [15]:
print(arr.size)
print(nd_arr.size)

5
12


### to get a structure of array

In [ ]:
print(arr.shape)
print(nd_arr.shape)

(5,)
(3, 4)


* first number means a number of rows
* second number means a number of columns

### to get byte size of one item of array

In [18]:
print(arr.itemsize, 'byte = 8 bit')
print(nd_arr.itemsize, 'byte = 16 bit')

1 byte = 8 bit
2 byte = 16 bit


### to add an empty array 

In [23]:
em_arr_1d = np.zeros(5, dtype=np.float16)
print(em_arr_1d)

em_arr_2d = np.zeros((3,4), dtype=np.float32)
print(em_arr_2d)

em_arr_3d = np.zeros((3,4,3), dtype=np.float32)
print(em_arr_3d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### to add a range array

In [29]:
ra_arr = np.arange(5, dtype=np.float16)
print(ra_arr)

ra_arr = np.arange(2,5, dtype=np.float16)
print(ra_arr)

ra_arr = np.arange(2,5,0.5, dtype=np.float16)
print(ra_arr)

[0. 1. 2. 3. 4.]
[2. 3. 4.]
[2.  2.5 3.  3.5 4.  4.5]
