# array functions

In [303]:
import numpy as np

In [304]:
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


### to change a shape

In [305]:
arr.shape = (2,4)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [306]:
arr_new = arr.reshape((2,4))
print(arr_new)

[[0 1 2 3]
 [4 5 6 7]]


### to change shape of array to order
* order='c' is a default, array is filled in line by line
* order='f' array is filled in by columns

In [307]:
arr_00 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]
                  ])
print(arr_00)
print('-------------')
arr_01 = arr_00.reshape((4,2), order="F")
print(arr_01)


[[1 2 3 4]
 [5 6 7 8]]
-------------
[[1 3]
 [5 7]
 [2 4]
 [6 8]]


### to transpose array

In [308]:
arr = np.arange(10)
arr.shape = (2,5)
print(arr)

arr_t = arr.transpose()
print(arr_t)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### sections of 1d array

In [309]:
arr_02 = np.linspace(0, 1, 9)
print(arr_02)
print('--------------------------')
print(arr_02[2])
print('--------------------------')
print(arr_02[0:2])
print('--------------------------')
print(arr_02[::-1])

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
--------------------------
0.25
--------------------------
[0.    0.125]
--------------------------
[1.    0.875 0.75  0.625 0.5   0.375 0.25  0.125 0.   ]


### sections of 2d array

In [310]:
arr_03 = np.linspace(0, 1, 9).reshape(3,3)
print(arr_03)
print('--------------------------')
print(arr_03[0])
print('--------------------------')
print(arr_03[::-1,-1])

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
--------------------------
[0.    0.125 0.25 ]
--------------------------
[1.    0.625 0.25 ]


### to sort 1d array

* method 1

In [311]:
arr_04 = np.array([12, 23, 56, 1, 4, 3, 17])
print(arr_04)
arr_05 = np.sort(arr_04)
print(arr_05)

[12 23 56  1  4  3 17]
[ 1  3  4 12 17 23 56]


* method 2

In [312]:
print(arr_04.sort())
print(arr_04)

None
[ 1  3  4 12 17 23 56]


### zero data

In [313]:
arr_06 = np.array([4, -9, 16, -36])
print(arr_06)
roots = np.sqrt(arr_06)
print(roots)

[  4  -9  16 -36]
[ 2. nan  4. nan]


C:\Users\Кипарис\AppData\Local\Temp\ipykernel_496\1159817455.py:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(arr_06)


### nan is not a number
* np.nan is class 'float', not class 'NoneType'

In [314]:
print(type(None))
print(type(np.nan))
print(None == None)
print(np.nan == np.nan)
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

<class 'NoneType'>
<class 'float'>
True
False
True
True
False


In [315]:
print(roots)
print(np.isnan(roots))
print(roots[np.isnan(roots)])
roots[np.isnan(roots)] = (9,36)
print(roots)

[ 2. nan  4. nan]
[False  True False  True]
[nan nan]
[ 2.  9.  4. 36.]
