# array

### array is a data type that:
* items are stored in order
* each item is avalible by index for same time
* all items has common data type
* max len of items and amount of memmory set in advance


In [2]:
import numpy as np

In [4]:
arr_00 = np.array([1, 2, 3, 4, 5])
print(type(arr_00))
print(arr_00)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
arr_01 = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]
                  ])
print(arr_01)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### to set a date type
int64 is default date type for numpy

In [9]:
arr_00 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(type(arr_00))
print(type(arr_00[0]))
print(arr_00)

<class 'numpy.ndarray'>
<class 'numpy.int8'>
[1 2 3 4 5]
