# array functions

In [33]:
import numpy as np

In [34]:
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


### to change a shape

In [35]:
arr.shape = (2,4)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [50]:
arr_new = arr.reshape((2,4))
print(arr_new)

[[0 1 2 3]
 [4 5 6 7]]


### to change shape of array to order
* order='c' is a default, array is filled in line by line
* order='f' array is filled in by columns

In [ ]:
arr_00 = np.arange(10)
arr_00.shape=(2,5)
print(arr_00)
print('-------------')

arr_01 = arr_00.reshape((2,5), order="C")
print(arr_01)
print('-------------')

arr_01 = arr_00.reshape((2,5), order="F")
print(arr_01)
print('-------------')

arr_01 = arr_00.reshape((2,5), order="A")
print(arr_01)

[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------
[[0 1 2 3 4]
 [5 6 7 8 9]]


### to transpose array

In [ ]:
arr = np.arange(10)