# numpy practice

In [3]:
import numpy as np

### task 0
Write the function, that takes argument "square's side lenth" as "a", and returns 2d array form a*a. The array must be filled with "1" and "0" in chessboard order.
* start with "0"
* use np.zeros 
* use slices
* no use cycles

In [4]:
def get_chess(a):
    arr = np.zeros((a,a), dtype=np.uint8)
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

get_chess(a=4)

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]], dtype=uint8)

### task 1
Write the function, that takes argument "array". The function must ganerate random number between 0 to uint32 for seed, and shafful items of array. The function returns a tuple with random number, and shaffuled array.
* the original array must remain unchanged
* the seed number must remain unchanged

In [5]:
def shuffle_seed(array):
    rm_seed = np.random.randint(0,4294967295,dtype=np.int64)
    np.random.seed(rm_seed)
    return (np.random.permutation(array), rm_seed)

array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([5, 2, 4, 1, 3]), np.int64(3517499721))

### task 2
Write the function, that takes unlimited number of vectors as input. The function returns min and max distance between vectors, as a tuple.
* it is guaranteed, that all vectors are same lenth

bad solution

In [6]:
def min_max_dist(*vectors):
    all_vec = [*vectors]
    result = list()
    for i in all_vec:
        for j in all_vec:
            if i is not j:
                result.append(np.linalg.norm(i - j))        
    return (np.min(result),np.max(result))

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

(np.float64(5.196152422706632), np.float64(10.392304845413264))

good solution

In [7]:
def min_max_dist(*vectors):
    result = list()
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            result.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (np.min(result), np.max(result))

min_max_dist(vec1, vec2, vec3)

(np.float64(5.196152422706632), np.float64(10.392304845413264))

### task 3
Write the function, that takes unlimited number of vectors as input. The function returns "True", if there is one pair of perpendicular vectors or more, or returns "False", if there isn't one.
* it is guaranteed, that all vectors are same lenth

bad solution

In [8]:
def any_normal(*vectors):
    result = list()
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            result.append(np.dot(vectors[i], vectors[j]))
    if 0 in result:
        return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

any_normal(vec1, vec2, vec3)

True

good solution

In [9]:
def any_normal(*vectors):
    result = list()
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

any_normal(vec1, vec2, vec3)
        

True

### Task 4
Write the function, that takes number of array parts as input, and generates 3d array of random numbers, between 1 to 100. The function returns a 5x5 array of random numbers.
* numbers must be int



In [10]:
def get_loto(num):
    arr = np.random.randint(1, 101, size=(num, 5, 5))
    return arr
get_loto(num=3)

array([[[ 81,  76,  16,  16,  81],
        [ 80,  61,  44,   7,  54],
        [ 13,  82,  66,   4,  90],
        [ 74, 100,   4,  71,  72],
        [ 41,  62,  52,  74,   7]],

       [[ 60,  36,  71,  44,   9],
        [ 61,  54, 100,  35,  21],
        [ 96,   4,  57,  19,  12],
        [ 61,  50,  15,  85,  18],
        [ 71,   2,  93,  80,  31]],

       [[ 88,  17,  32,  71,  28],
        [ 18,  92,  97,  24,  44],
        [ 54,  95, 100,  65,  53],
        [ 69,  74,  32,  67,  25],
        [  4,  59,  50,  75,  25]]], dtype=int32)

### Task 5
Write the function, that takes number of array parts as input, and generates 3d array of random numbers, between 1 to 100. The function returns a 5x5 array of random numbers.
* numbers must be int
* numbers shouldn't repeated

In [22]:
def get_unique_loto(num):
    i = 0
    lst_100 = np.arange(1, 101)
    arr = np.zeros((num,5,5))
    while i < num:
        arr[i,::,::] = np.random.choice(lst_100, size=(5,5), replace=False)
        i += 1    
    return arr
get_loto(num=3)

array([[[24., 32., 73., 99., 43.],
        [34., 82., 41., 14.,  1.],
        [92.,  4., 35., 81., 66.],
        [ 6., 69., 53., 17., 76.],
        [ 5., 10.,  9., 89., 97.]],

       [[28.,  3., 74., 14., 19.],
        [69., 57., 13., 90., 44.],
        [61., 77.,  8., 98., 39.],
        [71., 66., 40., 86., 92.],
        [33.,  2., 60., 79., 83.]],

       [[38., 57., 84., 35., 49.],
        [83., 69., 40., 33., 81.],
        [20., 56., 73., 37., 22.],
        [12., 77., 26., 82., 89.],
        [60., 13., 55., 62., 90.]]])