# random numbers

In [71]:
import numpy as np

### float random numbers

.rand()

In [72]:
np.random.rand()

0.19917743597210624

In [73]:
np.random.rand(5)

array([0.55577073, 0.95838571, 0.75939182, 0.42861427, 0.68779926])

In [74]:
np.random.rand(3,2)

array([[0.48512662, 0.82287006],
       [0.33909998, 0.62402553],
       [0.1299863 , 0.13311793]])

.sample()

In [75]:
np.random.sample((2,3))

array([[0.97687489, 0.55238942, 0.4580375 ],
       [0.60921916, 0.6858545 , 0.05483859]])

.uniform()

In [76]:
np.random.uniform(0, 10)

9.659078236972476

In [77]:
np.random.uniform(0, 10, size=(2,3))

array([[6.87788424, 7.20019694, 2.52291454],
       [5.91843684, 7.98381371, 8.04660798]])

### int random number

.randint()

In [78]:
np.random.randint(0,5)

3

In [79]:
np.random.randint(0,5,size=(2,2))

array([[3, 2],
       [0, 0]], dtype=int32)

### to shuffle numbers

In [80]:
arr = np.arange(6)
print(arr)
arr0 = np.random.shuffle(arr)
print(arr0)
print(arr)

[0 1 2 3 4 5]
None
[1 2 4 3 5 0]


In [81]:
arr0 = np.array([1, 2, 3, 4, 5])
arr1 = np.random.permutation(arr0)
print(arr0)
print(arr1)


[1 2 3 4 5]
[1 5 2 4 3]


### rabdom choice

In [82]:
arr0 = np.array([1, 2, 3, 4, 5])
arr1 = np.random.choice(arr0, size=(3,3), replace=True)
print(arr1)
arr1 = np.random.choice(arr0, size=(5), replace=False)
print(arr1)


[[4 2 2]
 [1 2 1]
 [3 5 1]]
[1 5 3 2 4]


### seed 
* max value of seed is uint32

In [83]:
np.iinfo(np.uint32)

iinfo(min=0, max=4294967295, dtype=uint32)

In [84]:
np.random.seed(12)
np.random.randint(0,100)

75

In [ ]:
import numpy as np
np.random.seed(2021)

simple = np.random.rand()
randoms = np.random.randint(-150,2021, size=120)
table = np.random.randint(1,101,size=(3,2))
even = np.array(list(filter(lambda x:x%2==0, range(2,17))))
mix = np.random.permutation(even.copy())
select = np.random.choice(mix, size=3, replace=False)
triplet =np.random.permutation(select)