# vectors

In [27]:
import numpy as np

### vectors must be same length

### to vectors sum

In [28]:
vec1 = np.array([2, 17, 21, 6])
vec2 = np.array([23, 8, 4, 19])
print(vec1 + vec2)

[25 25 25 25]


In [29]:
lst1 = [2, 17, 21, 6]
lst2 = [23, 8, 4, 19]
print(lst1 + lst2)

print([x + y for x, y in zip(lst1, lst2)])

[2, 17, 21, 6, 23, 8, 4, 19]
[25, 25, 25, 25]


### vector subtraction

In [30]:
print(vec1 - vec2)

[-21   9  17 -13]


### vectors multiplication

In [31]:
vec3 = np.array([2, 4, 6, 8])
print(vec3*5)
print(vec3**2)
print(vec3**0.5)

[10 20 30 40]
[ 4 16 36 64]
[1.41421356 2.         2.44948974 2.82842712]


### vectors dividing

In [32]:
vec1 = np.array([2, 17, 21, 6])
vec2 = np.array([23, 8, 4, 19])
print(vec1 / vec2)
print(vec1 // vec2)
print(vec1 % vec2)
print(vec1 / 2)

[0.08695652 2.125      5.25       0.31578947]
[0 2 5 0]
[2 1 1 6]
[ 1.   8.5 10.5  3. ]


### vector comparison

In [33]:
print(vec1 > vec2)
print(vec3 > 5)

[False  True  True False]
[False False  True  True]
