# vectors

In [20]:
import numpy as np

### vectors must be same length

### to vectors sum

In [21]:
vec1 = np.array([2, 17, 21, 6])
vec2 = np.array([23, 8, 4, 19])
print(vec1 + vec2)

[25 25 25 25]


In [22]:
lst1 = [2, 17, 21, 6]
lst2 = [23, 8, 4, 19]
print(lst1 + lst2)

print([x + y for x, y in zip(lst1, lst2)])

[2, 17, 21, 6, 23, 8, 4, 19]
[25, 25, 25, 25]


### vector subtraction

In [23]:
print(vec1 - vec2)

[-21   9  17 -13]


### vectors multiplication

In [24]:
vec3 = np.array([2, 4, 6, 8])
print(vec3*5)
print(vec3**2)
print(vec3**0.5)

[10 20 30 40]
[ 4 16 36 64]
[1.41421356 2.         2.44948974 2.82842712]


### vectors dividing

In [25]:
vec1 = np.array([2, 17, 21, 6])
vec2 = np.array([23, 8, 4, 19])
print(vec1 / vec2)
print(vec1 // vec2)
print(vec1 % vec2)
print(vec1 / 2)

[0.08695652 2.125      5.25       0.31578947]
[0 2 5 0]
[2 1 1 6]
[ 1.   8.5 10.5  3. ]


### vector comparison

In [26]:
print(vec1 > vec2)
print(vec3 > 5)

[False  True  True False]
[False False  True  True]


### vectot lenth
* v_len = (x^2 + x^2 + ...)**0.5

In [27]:
vec4 = np.array([3, 4])
v_len = np.sqrt(np.sum(vec4**2))
print(v_len)

5.0


In [28]:
v_len = np.linalg.norm(vec4)
print(v_len)

5.0


### distance vectors
* v_dis = ((x - y)^2 + (x - y)^2 + ... )**0.5

In [29]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
v_dis = np.sqrt(np.sum((vec1 - vec2)**2))
print(v_dis)

12.206555615733702


In [30]:
v_dis = np.linalg.norm(vec1 - vec2)
print(v_dis)

12.206555615733702


### scalar product/vector's dot
* v_dot = (x * y) + (x * y) + ...  

In [31]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
v_dot = np.sum(vec1 * vec2)
print(v_dot)

47


In [32]:
v_dot = np.dot(vec1, vec2)
print(v_dot)

47


### vector's statictic functions

In [35]:
vec5 = np.array([1458, 75, 633, 899, 11, 7, 15, 3354])

### to get vector's median

In [36]:
mdn = np.median(vec5)
print(mdn)

354.0


### to get vector's mean

In [37]:
men = np.mean(vec5)
print(men)

806.5


### to get vector's standart deviation

In [38]:
dev = np.std(vec5)
print(dev)

1083.192734466032


### to get vector's percentile

In [42]:
prc = np.percentile(vec5, 70)
print(prc)

872.3999999999999


### to get vector's min and max

In [44]:
n_mn = np.min(vec5)
n_mx = np.max(vec5)
print('min=', n_mn, 'max=', n_mx)

min= 7 max= 3354
