# random numbers

In [2]:
import numpy as np

### float random numbers

.rand()

In [3]:
np.random.rand()

0.20041954318840216

In [4]:
np.random.rand(5)

array([0.83166058, 0.8094528 , 0.44503101, 0.76095499, 0.96468104])

In [5]:
np.random.rand(3,2)

array([[0.28165249, 0.20236132],
       [0.72732392, 0.14676092],
       [0.64933839, 0.12673794]])

.sample()

In [6]:
np.random.sample((2,3))

array([[0.14232071, 0.19132769, 0.46357479],
       [0.73508365, 0.49109412, 0.26919085]])

.uniform()

In [7]:
np.random.uniform(0, 10)

0.9534349602773484

In [8]:
np.random.uniform(0, 10, size=(2,3))

array([[4.13527538, 6.57040864, 5.07689082],
       [6.80173655, 6.68147982, 0.9649566 ]])

### int random number

.randint()

In [9]:
np.random.randint(0,5)

0

In [10]:
np.random.randint(0,5,size=(2,2))

array([[0, 0],
       [3, 0]], dtype=int32)

### to shuffle numbers

In [ ]:
arr = np.arange(6)
print(arr)
arr0 = np.random.shuffle(arr)
print(arr0)
print(arr)

[0 1 2 3 4 5]
[1 0 2 4 5 3]


In [22]:
arr0 = np.array([1, 2, 3, 4, 5])
arr1 = np.random.permutation(arr0)
print(arr0)
print(arr1)


[1 2 3 4 5]
[3 4 5 1 2]


### rabdom choice

In [13]:
arr0 = np.array([1, 2, 3, 4, 5])
arr1 = np.random.choice(arr0, size=(3,3), replace=True)
print(arr1)
arr1 = np.random.choice(arr0, size=(5), replace=False)
print(arr1)


[[2 3 4]
 [3 4 1]
 [3 3 2]]
[2 4 5 1 3]


### seed 
* max value of seed is uint32

In [14]:
np.iinfo(np.uint32)

iinfo(min=0, max=4294967295, dtype=uint32)

In [15]:
np.random.seed(12)
np.random.randint(0,100)

75